# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='useraddress',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
